import { SkillRegistry } from "./registry";
import { readFileSkill } from "./local/read_file";
import { writeFileSkill } from "./local/write_file";
import { listFilesSkill } from "./local/list_files";
import { searchTextSkill } from "./local/search_text";
import { runTestsSkill } from "./local/run_tests";
import { logInteractionSkill } from "./memory/log_interaction";
import { writeSessionSummarySkill } from "./memory/write_session_summary";
import { promoteToCanonMemorySkill } from "./memory/promote_to_canon_memory";
import { queryCanonMemorySkill } from "./memory/query_canon_memory";
import { searchRawLogsSkill } from "./memory/search_raw_logs";
import { memoryAddSkill } from "./memory/memory_add";
import { memorySearchSkill } from "./memory/memory_search";
import { memoryGetSkill } from "./memory/memory_get";
import { memoryListSkill } from "./memory/memory_list";
import { listKnowledgeSkill } from "./knowledge/list_knowledge";
import { searchKnowledgeSkill } from "./knowledge/search_knowledge";
import { addKnowledgeDocSkill } from "./knowledge/add_knowledge_doc";
import { listToolsSkill } from "./tools/list_tools";
import { recommendToolSkill } from "./tools/recommend_tool";
import { sendEmailSkill } from "./outbound/send_email";
import { requestPaymentSkill } from "./outbound/request_payment";
import { makeCallSkill } from "./outbound/make_call";
import { sendHttpRequestSkill } from "./network/send_http_request";
import { sendEmailRequestSkill } from "./outbound/send_email_request";
import { requestPhoneCallSkill } from "./outbound/request_phone_call";
import { requestWebBuildSkill } from "./requests/request_web_build";
import { requestDocPackSkill } from "./requests/request_doc_pack";
import { requestVideoEditSkill } from "./requests/request_video_edit";
import { requestImageEditSkill } from "./requests/request_image_edit";
import { requestClientIntakeSkill } from "./requests/request_client_intake";
import { requestNegotiationScriptSkill } from "./requests/request_negotiation_script";
import { requestFollowUpSkill } from "./requests/request_follow_up";
import { requestRecommendationRequestSkill } from "./requests/request_recommendation_request";
import { runPacketSkill } from "./runner/run_packet";
import { recommendLlmSkill } from "./llm/recommend_llm";
import { analyzeInputRiskSkill } from "./security/analyze_input_risk";
import { freezeSystemSkill } from "./security/freeze_system";
import { unfreezeSystemSkill } from "./security/unfreeze_system";

export function buildRegistry(): SkillRegistry {
  const registry = new SkillRegistry();
  registry.register(readFileSkill);
  registry.register(writeFileSkill);
  registry.register(listFilesSkill);
  registry.register(searchTextSkill);
  registry.register(runTestsSkill);
  registry.register(logInteractionSkill);
  registry.register(writeSessionSummarySkill);
  registry.register(promoteToCanonMemorySkill);
  registry.register(queryCanonMemorySkill);
  registry.register(searchRawLogsSkill);
  registry.register(memoryAddSkill);
  registry.register(memorySearchSkill);
  registry.register(memoryGetSkill);
  registry.register(memoryListSkill);
  registry.register(listKnowledgeSkill);
  registry.register(searchKnowledgeSkill);
  registry.register(addKnowledgeDocSkill);
  registry.register(listToolsSkill);
  registry.register(recommendToolSkill);
  registry.register(sendEmailSkill);
  registry.register(requestPaymentSkill);
  registry.register(makeCallSkill);
  registry.register(sendHttpRequestSkill);
  registry.register(sendEmailRequestSkill);
  registry.register(requestPhoneCallSkill);
  registry.register(requestWebBuildSkill);
  registry.register(requestDocPackSkill);
  registry.register(requestVideoEditSkill);
  registry.register(requestImageEditSkill);
  registry.register(requestClientIntakeSkill);
  registry.register(requestNegotiationScriptSkill);
  registry.register(requestFollowUpSkill);
  registry.register(requestRecommendationRequestSkill);
  registry.register(runPacketSkill);
  registry.register(recommendLlmSkill);
  registry.register(analyzeInputRiskSkill);
  registry.register(freezeSystemSkill);
  registry.register(unfreezeSystemSkill);
  return registry;
}
